### ISSUE TITLE
Consider webpack 2@beta

### ISSUE THREAD

**Issue by TheLarkInn** [keawade/react-typescript-boilerplate#2]
Hey great boilerplate! Would love to see this using webpack@2.1.0-beta.25

We added some great features to .25 including configuration validation, would lead to an overall better webpack experience for users!!!

**Comment by keawade** [comment]
Thanks for the feedback! I've just finished updating to beta.25.

A few notes on the experience:
- I like the new `rules` config style.
- The configuration validation is _really_ nice and was invaluable for figuring out what changes I needed to make to update.
- There seems to be next to nothing for documentation. I ended up dropping out my tslint config option to fail on warning (for now) because I wasn't able to get the validator's suggested `LoaderOptionsPlugin()` working in its stead. The closest things I found to docs were an [old gist from v2.0.5-beta](https://gist.github.com/sokra/27b24881210b56bbaff7) and the release notes from [beta.23 - beta.25](https://github.com/webpack/webpack/releases).

I look forward to getting some more detailed docs so I can improve my builds. Thanks again for the suggestion!
